/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package critipediainterface_uno_dos;

/**
 *
 * @author rafa_
 */
public class PantallaNotificaciones extends javax.swing.JPanel {

    
    private CuadroBase cuadro;
   
    /** Creates new form PantallaNotificaciones */
    public PantallaNotificaciones(CuadroBase cuadro) {
        initComponents();
        
        this.cuadro = cuadro;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagenSerie = new javax.swing.JLabel();
        pnBotones = new javax.swing.JPanel();
        btnPantallaPrincipal = new javax.swing.JButton();
        btnPantallaMiPerfil = new javax.swing.JButton();
        btnPantallaDescubre = new javax.swing.JButton();
        btnPantallaContenido = new javax.swing.JButton();
        btnPantallaNotificaciones = new javax.swing.JButton();
        pnCometarios = new javax.swing.JPanel();
        lblTuComentario = new javax.swing.JLabel();
        lblRespuesta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnContestar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReRespuesta = new javax.swing.JTextArea();
        btnVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(249, 235, 226));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(1366, 768));

        lblImagenSerie.setText("Foto de la Serie que se comentó");
        lblImagenSerie.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblImagenSerie.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnBotones.setBackground(new java.awt.Color(249, 235, 226));
        pnBotones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPantallaPrincipal.setBackground(new java.awt.Color(249, 200, 169));
        btnPantallaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconCritipedia2.png"))); // NOI18N
        btnPantallaPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPantallaPrincipal.setContentAreaFilled(false);
        btnPantallaPrincipal.setOpaque(true);
        btnPantallaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantallaPrincipalActionPerformed(evt);
            }
        });

        btnPantallaMiPerfil.setBackground(new java.awt.Color(249, 200, 169));
        btnPantallaMiPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/profile.png"))); // NOI18N
        btnPantallaMiPerfil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPantallaMiPerfil.setContentAreaFilled(false);
        btnPantallaMiPerfil.setOpaque(true);
        btnPantallaMiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantallaMiPerfilActionPerformed(evt);
            }
        });

        btnPantallaDescubre.setBackground(new java.awt.Color(249, 200, 169));
        btnPantallaDescubre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/descubre.png"))); // NOI18N
        btnPantallaDescubre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPantallaDescubre.setContentAreaFilled(false);
        btnPantallaDescubre.setOpaque(true);
        btnPantallaDescubre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantallaDescubreActionPerformed(evt);
            }
        });

        btnPantallaContenido.setBackground(new java.awt.Color(249, 200, 169));
        btnPantallaContenido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/contenido.png"))); // NOI18N
        btnPantallaContenido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPantallaContenido.setContentAreaFilled(false);
        btnPantallaContenido.setOpaque(true);
        btnPantallaContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantallaContenidoActionPerformed(evt);
            }
        });

        btnPantallaNotificaciones.setBackground(new java.awt.Color(249, 200, 169));
        btnPantallaNotificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/notificacion.png"))); // NOI18N
        btnPantallaNotificaciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPantallaNotificaciones.setContentAreaFilled(false);
        btnPantallaNotificaciones.setOpaque(true);

        javax.swing.GroupLayout pnBotonesLayout = new javax.swing.GroupLayout(pnBotones);
        pnBotones.setLayout(pnBotonesLayout);
        pnBotonesLayout.setHorizontalGroup(
            pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotonesLayout.createSequentialGroup()
                .addComponent(btnPantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(btnPantallaMiPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(btnPantallaNotificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(btnPantallaContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addComponent(btnPantallaDescubre, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
        );
        pnBotonesLayout.setVerticalGroup(
            pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotonesLayout.createSequentialGroup()
                .addGroup(pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPantallaMiPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPantallaDescubre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPantallaContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPantallaNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pnCometarios.setBackground(new java.awt.Color(249, 235, 226));
        pnCometarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTuComentario.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        lblTuComentario.setText("Aquí irá escrito el cometario de la persona.");

        lblRespuesta.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        lblRespuesta.setText("Aquí irá la respuesta de otro usuario a tu comentario.");
        lblRespuesta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblRespuesta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Foto del usuario que responde");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnCometariosLayout = new javax.swing.GroupLayout(pnCometarios);
        pnCometarios.setLayout(pnCometariosLayout);
        pnCometariosLayout.setHorizontalGroup(
            pnCometariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCometariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(lblRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(pnCometariosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTuComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCometariosLayout.setVerticalGroup(
            pnCometariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCometariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTuComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnCometariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        btnContestar.setBackground(new java.awt.Color(249, 200, 169));
        btnContestar.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnContestar.setText("Contestar");
        btnContestar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnContestar.setContentAreaFilled(false);
        btnContestar.setOpaque(true);

        btnEnviar.setBackground(new java.awt.Color(249, 200, 169));
        btnEnviar.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnviar.setContentAreaFilled(false);
        btnEnviar.setOpaque(true);

        txtReRespuesta.setColumns(20);
        txtReRespuesta.setRows(5);
        txtReRespuesta.setEnabled(false);
        jScrollPane1.setViewportView(txtReRespuesta);

        btnVolver.setBackground(new java.awt.Color(249, 200, 169));
        btnVolver.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.setContentAreaFilled(false);
        btnVolver.setOpaque(true);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagenSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnContestar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41))
                            .addComponent(pnCometarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagenSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCometarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnContestar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addContainerGap(116, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
    }// </editor-fold>//GEN-END:initComponents
                                  
    
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        cuadro.getContentPane().removeAll();
        
        EventosDeBoton.volver(cuadro);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnPantallaMiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantallaMiPerfilActionPerformed
        cuadro.getContentPane().removeAll();
        
        EventosDeBoton.llamaPantallaMiPerfil(cuadro);
    }//GEN-LAST:event_btnPantallaMiPerfilActionPerformed

    private void btnPantallaContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantallaContenidoActionPerformed
        cuadro.getContentPane().removeAll();
        
        EventosDeBoton.llamaPantallaContenido(cuadro);
    }//GEN-LAST:event_btnPantallaContenidoActionPerformed

    private void btnPantallaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantallaPrincipalActionPerformed
        cuadro.getContentPane().removeAll();
        
        EventosDeBoton.llamaPantallaPrincipal(cuadro);
    }//GEN-LAST:event_btnPantallaPrincipalActionPerformed

    private void btnPantallaDescubreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantallaDescubreActionPerformed
        cuadro.getContentPane().removeAll();
        
        EventosDeBoton.llamaPantallaDescubre(cuadro);
    }//GEN-LAST:event_btnPantallaDescubreActionPerformed

     
     
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContestar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnPantallaContenido;
    private javax.swing.JButton btnPantallaDescubre;
    private javax.swing.JButton btnPantallaMiPerfil;
    private javax.swing.JButton btnPantallaNotificaciones;
    private javax.swing.JButton btnPantallaPrincipal;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagenSerie;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblTuComentario;
    private javax.swing.JPanel pnBotones;
    private javax.swing.JPanel pnCometarios;
    private javax.swing.JTextArea txtReRespuesta;
    // End of variables declaration//GEN-END:variables

}
