/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author rafa_
 */
public class AboutUs extends javax.swing.JPanel {

    /**
     * Creates new form AboutUs
     */
    private CuadroBase cuadro;
    private PantallaInicio pi;
    public AboutUs(CuadroBase cuadro) {
        initComponents();
        
        this.cuadro = cuadro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        lblNombreUno1 = new javax.swing.JLabel();
        lblTareaDos = new javax.swing.JLabel();
        lblTareaUno = new javax.swing.JLabel();
        lblNombreUno = new javax.swing.JLabel();
        lblNombreDos = new javax.swing.JLabel();
        lblTareaTres = new javax.swing.JLabel();
        lblTareaCinco = new javax.swing.JLabel();
        lblTareaCuatro = new javax.swing.JLabel();
        lblNombreTres = new javax.swing.JLabel();
        lblNombreCuatro = new javax.swing.JLabel();
        lblNombreCinco = new javax.swing.JLabel();
        lblNombreSiete = new javax.swing.JLabel();
        lblNombreOcho = new javax.swing.JLabel();
        lblNombreSeis = new javax.swing.JLabel();
        lblAboutUs = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(249, 235, 226));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(670, 380));

        lblTitulo.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        lblTitulo.setText("CRITIPEDIA");

        lblVersion.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        lblVersion.setText("v 1.0 (Nov 2017)");

        lblNombreUno1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lblNombreUno1.setText("Carlos García González");

        lblTareaDos.setFont(new java.awt.Font("Lucida Bright", 3, 16)); // NOI18N
        lblTareaDos.setText("Implementación POJO's");

        lblTareaUno.setFont(new java.awt.Font("Lucida Bright", 3, 16)); // NOI18N
        lblTareaUno.setText("Análisis y Diseño");

        lblNombreUno.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lblNombreUno.setText("Carlos García González");

        lblNombreDos.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lblNombreDos.setText("Jose Ayala Bernal");

        lblTareaTres.setFont(new java.awt.Font("Lucida Bright", 3, 16)); // NOI18N
        lblTareaTres.setText("Creación de BBDD");

        lblTareaCinco.setFont(new java.awt.Font("Lucida Bright", 3, 16)); // NOI18N
        lblTareaCinco.setText("Interfaz de Usuario");

        lblTareaCuatro.setFont(new java.awt.Font("Lucida Bright", 3, 16)); // NOI18N
        lblTareaCuatro.setText("Metodología de Trabajo en Equipo");

        lblNombreTres.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lblNombreTres.setText("Daniel González Gómez");

        lblNombreCuatro.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lblNombreCuatro.setText("Alberto Heredia Torres");

        lblNombreCinco.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lblNombreCinco.setText("Mª Victoria García Armario");

        lblNombreSiete.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lblNombreSiete.setText("Marco A.Cordero Vidal");

        lblNombreOcho.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lblNombreOcho.setText("Rafael Lebrón Peña");

        lblNombreSeis.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lblNombreSeis.setText("Fco. José Hidalgo Garrido");

        lblAboutUs.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        lblAboutUs.setText("<html>&nbsp;&nbsp;Critipedia es un proyecto en el que nos embarcamos los alumnos de segundo curso de <br> Desarrollo de Aplicaciones Multiplataforma del Instituto Ies Almunia en Jerez de la Frontera junto con nuestro profesor de Programación Luis Manuel Vázquez Venegas.<br>En esta versión de aplicación se podrán hacer críticas sobre películas y series que hayamos visto, y tendremos la posibilidad de responder a críticas de otros usuarios. </html>");
        lblAboutUs.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnVolver.setBackground(new java.awt.Color(249, 200, 169));
        btnVolver.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.setContentAreaFilled(false);
        btnVolver.setOpaque(true);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTareaDos)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombreUno1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreDos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTareaUno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNombreUno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTareaTres, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreTres))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTareaCinco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNombreSeis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNombreSiete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNombreOcho))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblAboutUs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblTareaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblNombreCuatro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblNombreCinco))))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVersion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(lblAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTareaUno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreUno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreDos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTareaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreUno1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTareaTres, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreTres, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTareaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreCuatro)
                    .addComponent(lblNombreCinco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTareaCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreSeis)
                    .addComponent(lblNombreSiete)
                    .addComponent(lblNombreOcho))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        cuadro.getContentPane().removeAll();

        pi = new PantallaInicio(cuadro);
        pi.setVisible(true);
        cuadro.add(pi);
        cuadro.validate();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblAboutUs;
    private javax.swing.JLabel lblNombreCinco;
    private javax.swing.JLabel lblNombreCuatro;
    private javax.swing.JLabel lblNombreDos;
    private javax.swing.JLabel lblNombreOcho;
    private javax.swing.JLabel lblNombreSeis;
    private javax.swing.JLabel lblNombreSiete;
    private javax.swing.JLabel lblNombreTres;
    private javax.swing.JLabel lblNombreUno;
    private javax.swing.JLabel lblNombreUno1;
    private javax.swing.JLabel lblTareaCinco;
    private javax.swing.JLabel lblTareaCuatro;
    private javax.swing.JLabel lblTareaDos;
    private javax.swing.JLabel lblTareaTres;
    private javax.swing.JLabel lblTareaUno;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVersion;
    // End of variables declaration//GEN-END:variables
}
